### PR TITLE
Remove HTTPS references for sources

### PR DESCRIPTION
**Pull request by ravolt**
We have a lot of places were we use HTTPS but don't need it.

HTTPS may be complicated by some corporate networks so it is good idea to avoid if possible

### CODE REVIEW

**Comment by VictorLowther** [comment]
-1.  Blindly changing https to http does not mean we will not use https -- rubygems urls (for example) just redirects you back to the https version of the URL.

**Comment by ravolt** [comment]
connect to #425

**Comment by ravolt** [comment]
@VictorLowther you are correct.  this pull is for review and testing.  I made the change for a specific user who thought they may have issues.  they are testing without the change first.

**Comment by cloudedge** [comment]
unneeded after review

**Pull request closed without merging**
